modules/admin/controllers/SettingsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Settings;
use yii\data\ActiveDataProvider;
use app\components\Controller;
use app\components\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SettingsController implements the CRUD actions for Settings model.
 */
class SettingsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),

                'rules' => [
                    [

                        'allow' => true,
                        'roles' => ["admin"],
                    ],
                ],
            ],


            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Settings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Settings::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Settings model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Settings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Settings();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Settings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionSave() {
        foreach ($_POST as $key => $value) {
            Settings::set($key, $value);
        }
    }

    /**
     * Deletes an existing Settings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Settings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Settings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Settings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/settings/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Settings */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="settings-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'key')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'value')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/settings/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Settings */

$this->title = 'Create Settings';
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="settings-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/settings/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use app\models\Settings;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<h2>Настройки</h2>

<div class="row">
    <div class="col-md-6 col-lg-6 col-xlg-4">
        <div class="panel">
            <div class="panel-header header-line">
                <h3>Доступ к <strong>Yandex Metrika</strong></h3>
            </div>
            <div class="panel-content">
                <p>
                    Укажите здесь <b>oauth_token</b> для доступа к счетчикам вашего аккаунта yandex.
                    Для получения токена воспользуйтесь <a href="https://oauth.yandex.ru/authorize?response_type=token&client_id=342e8529f69b4cb497e87836052df7fa" >авторизацией</a>.
                    <br> <br>
                    Счетчик автоматически будет подключен к сайту, а информация о посещениях будет отображена на главной странице панели администратора.
                </p>

                <form class="form-horizontal" id="yandex-metrika-form">
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?=Settings::title("yandex_token")?></label>
                        <div class="col-sm-8">
                            <input class="form-control" type="text" name="yandex_token" value="<?=Settings::get("yandex_token")?>" placeholder="OAuth-токен Yandex">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?=Settings::title("yandex_counter")?></label>
                        <div class="col-sm-8">
                            <input class="form-control" type="text" name="yandex_counter" value="<?=Settings::get("yandex_counter")?>" placeholder="ID счетчика">
                        </div>
                    </div>
                </form>

            </div>
            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <button type="button" class="btn btn-primary ladda-button btn-save" data-style="expand-right" data-id="yandex" >Сохранить</button>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-lg-6 col-xlg-4">
        <div class="panel">
            <div class="panel-header header-line">
                <h3>Настройки <strong>сайта</strong></h3>
            </div>
            <div class="panel-content">

                <p>
                    Вы можете самостоятельно изменить некоторые настройки сайта. <br>
                </p>

                <h3><strong>Мета-теги</strong> сайта</h3>

                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-6">
                        <p>
                            Позволяют управлять служебной информацией сайта
                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-6">
                        <a href="<?= Url::toRoute(["/admin/meta-tags"])?>" class="btn btn-block btn-primary">Редактировать</a>
                    </div>
                </div>

            </div>
            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <button type="button" class="btn btn-primary ladda-button btn-save" data-style="expand-right" data-id="yandex" >Сохранить</button>
                </div>
            </div>
        </div>
    </div>

</div>

<script>

    var saveButtons = {};
    $(document).ready(function() {

        $(".btn-save").each(function() {
            saveButtons[$(this).data("id")] = Ladda.create(this);
        }).click(function() {

            var form = $(this).parents(".panel").find("form");

            var btn = this;
            var ladda = saveButtons[$(btn).data("id")];
            ladda.start();

            $.ajax({
                url: "<?=Url::toRoute("settings/save")?>",
                type: "post",
                data: $(form).serialize(),
                success: function(data) {
                    console.log(data);
                    $(btn).html("Сохранено").removeClass("btn-primary").addClass("btn-success");
                    ladda.stop();
                }
            })
        })

        var params = $.deparam.fragment();
        if (params.access_token) {
            $("input[name='yandex_token").val(params.access_token);
            $(".btn-save[data-id='yandex'").click()
        }


    })
</script>

modules/admin/views/settings/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Settings */

$this->title = 'Update Settings: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="settings-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/settings/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Settings */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="settings-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'key',
            'value',
        ],
    ]) ?>

</div>